CMakeLists.txt
Like this we can overwrite it's value from the commandline via
`-DBoost_USE_STATIC_LIBS=OFF`.
Linux distributions will prefer this.
=> Make Boost_USE_STATIC_LIBS a cache variable

src/lib_utility/utility/utilityString.cpp
elide() needs to always return std:string.
We cover all cases because our switch contains all current possibilities
for ElideMode.
But the compiler will still warn/error on this, depending on system
configuration.
I would like to add a `return "";` or `return str;` or add a `default:`
case to the switch to silence this compiler complaint.
=> Always return a value from non void function elide()

src/lib/data/search/SearchMatch.cpp
getSearchTypeName() needs to always return std:wstring.
We cover all cases because our switch contains all current possibilities
for Search_Type.
But the compiler will still warn/error on this, depending on system
configuration.
=> src: Always return a value from non void function getSearchTypeName()

src/lib_gui/qt/project_wizard/content/QtProjectWizardContentSelect.cpp
Modern CMakes seem to need need -DCMAKE_EXPORT_COMPILE_COMMANDS=ON instead of -DCMAKE_EXPORT_COMPILE_COMMANDS=1
=> In modern CMakes yes is "ON" not 1

CMakeLists.txt
The last part should be quoted, or there might be error like
```
CMake Error at CMakeLists.txt:680 (STRING):
STRING sub-command REGEX, mode REPLACE needs at least 6 arguments total to
command.
```
=> Fix a possible cmake error on macOS

src/lib/component/ComponentManager.cpp, src/lib/data/graph/Token.h, src/lib_cxx/utility/codeblocks/CodeblocksCompiler.h
I've caught an exeption on app exit:
> Exception thrown: read access violation.
> screenSearchSender->**** was 0xFFFFFFFFFFFFFFE7
The problem is that `TabsController` depends on `ScreenSearchController` and  `ScreenSearchController` gets destroyed before `TabsController` leaving him hanging on a dead object.
The proposed solution is to destroy components in the order reverse to creation
Steps to reproduce:
1) start sourcetrail
2) open any project for example 'tutorial.srctrlprj'
3) close sourcetrail
<details>
<summary>Full stacktrace</summary>
```
Sourcetrail.exe!ComponentManager::teardownTab(ScreenSearchSender * screenSearchSender) Line 200	C++
Sourcetrail.exe!Tab::~Tab() Line 22	C++
Sourcetrail.exe!Tab::`scalar deleting destructor'(unsigned int)	C++ …
```
=> Fix crash on exit

CMakeLists.txt
Make MSVC compiler use all available cores during build
=> build: add multiprocessor compilation flag to cmake to speedup builds

CMakeLists.txt, appveyor.yml
ninja is not only faster than msbuild, but also brings some sanity to
the messages produced by compiler: first, it holds a lock over output,
only allowing single process to write at once; second: it reduces
verbosity to something palatable.
msbuild:
```
GraphViewStyle.cpp
C:\projects\sourcetrail\src\lib\component\view\GraphViewStyle.cpp(148): warning C4244: '=': conversion from 'float' to 'int', possible loss of data [C:\projects\sourcetrail\build\win64\Sourcetrail_lib.vcxproj]
C:\projects\sourcetrail\src\lib\component\view\GraphViewStyle.cpp(319): warning C4244: '=': conversion from 'size_t' to 'float', possible loss of data [C:\projects\sourcetrail\build\win64\Sourcetrail_lib.vcxproj]
C:\projects\sourcetrail\src\lib\component\view\GraphViewStyle.cpp(319): warning C4244: '=': conversion …
```
=> Use ninja on appveyor

src/lib_gui/qt/element/code/QtCodeArea.cpp, src/lib_gui/qt/element/code/QtCodeArea.h
Introduces the issue: during drag there's a lot of messages in debug console from Qt library:
`QPixmap::scaled: Pixmap is a null pixmap`
That's because we didn't specify the draggable preview for `QDrag` object.
I couldn't figure out the suitable image :)
Resolves #707
=> Drag and drop

src/app/main.cpp, src/lib/app/Application.cpp, src/lib/app/Application.h, src/lib/project/Project.cpp, src/lib/project/Project.h, src/lib/project/RefreshInfo.h, src/lib/utility/commandline/CommandLineParser.cpp, src/lib/utility/commandline/CommandLineParser.h, src/lib/utility/commandline/commands/CommandlineCommandIndex.cpp, src/lib/utility/messaging/type/MessageLoadProject.h
* added "--shallow" command line option to request shallow indexing
* modified behavior of Sourcetrail to always perform a deep index if not explicitly specified differently by the user
=> logic: improve usability of shallow indexing ui

docs/documentation/index.html
Before merging this change you need to fix the certificate for https://coati.io though :)
=> Replace unsafe http links with https in docs

CMakeLists.txt
Fixes the build on Gentoo Linux. On Gentoo Linux the user chooses which
llvm backend to build and install, therefore we need to loop over the
installed targets and append the libraries needed instead of relying on
the full list of supported backends.
=> Fixes build on Gentoo Linux

src/lib/component/controller/GraphController.cpp, src/lib/data/NodeType.cpp, src/lib/data/NodeType.h
During code review I found potential optimization.
Method getOverviewBundleNodeTypesOrdered is called by function GraphController::bundleNodesByType as vector of enums.
But this is not optimized so in assembly. 
and unfortunately:
Function by every call constructs whole vector. 
We can fix that situation by eliminating method call and making vector (array) static and const.  
Result after fix:
All tests passed.
=> perf: GetOverviewBundleNodeTypesOrdered to static const variable.

src/lib/component/controller/helper/DummyNode.h, src/lib_utility/utility/utilityString.cpp, src/lib_utility/utility/utilityString.h, src/test/UtilityStringTestSuite.cpp
Another performance improvement. This one is very impactful and improvement is quite noticeable.
It replaces two function calls utilities::toLowerCase and std::compare (by operator<).
Problem with old way was creating two additional strings every time when  DummyNodeComp function operator() was called (which is very often) and then making comparison.
New function utilities::caseInsensitiveLess do same logic but in place.
For this example data:
```
std::wstring str1 = L"1aaBcssdef";
std::wstring str2 = L"1aAbcssdefg_hijkds";
```
I've done benchmark by extraction utilities::toLowerCase implementation and comparison with utilities::caseInsensitiveLess. Test measured on Debian buster
with Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz.
Benchmark done on single isolated core with max scheduler …
=> perf: Added utilities::caseInsensitiveLess.

src/lib/utility/file/FilePath.cpp, src/lib/utility/file/FilePath.h, src/lib_gui/qt/project_wizard/content/QtProjectWizardContentProjectData.cpp
* added "isValid" to FilePath
* used "isValid" in check of selected project directory
=> logic: fix crash when project directory contains non-latin character (issue #899)

src/lib/data/storage/PersistentStorage.cpp, src/lib/data/storage/PersistentStorage.h
Overview graph performance improvement.
Method PersistenceStorage::getGraphForAll calls sqlliteIndexStorage two times:
1. During gathering of node ID's
2. When adding nodes to graph within PersistenceStorage::addNodesToGraph. 
Unfortunately during each of these calls all nodes are retrieved from database.
I rewritten this function. Merging logic from getGraphForAll and addNodesToGraph we can avoid second sql enumeration.
This operation gave me possibility to introduce additional optimizations e.g deletion of redundant checks and avoiding m_fileNodeIndexed enumeration.
Improvement in cycles is aprox. 8% - 15%.
Perf after load project, on debug build,  database linux-5.4.7 before improvement:
After improvement:
There is a possible removal of redundancy with `if …
=> perf: PersistentStorage::getGraphForAll - avoiding second sqlite call.

.gitignore, src/app/main.cpp, src/indexer/main.cpp, src/lib/app/Application.cpp, src/lib/settings/ApplicationSettings.cpp, src/lib/settings/ApplicationSettings.h, src/lib_gui/qt/project_wizard/content/QtProjectWizardContentPreferences.cpp, src/lib_gui/qt/project_wizard/content/QtProjectWizardContentPreferences.h, src/lib_gui/qt/window/QtMainWindow.cpp
=> Allow changing the log file path in preferences

src/lib/settings/Settings.cpp, src/lib/settings/Settings.h, src/lib/utility/ConfigManager.cpp, src/lib/utility/ConfigManager.h, src/lib_gui/qt/project_wizard/QtProjectWizard.cpp
=> ui: handle case when selected project location can not be written

src/lib_cxx/data/parser/cxx/CxxAstVisitorComponentIndexer.cpp
Fixes a crash I encounter with one of my C++ projects. I observed both `destroyedTypeQual.getTypePtrOrNull()` returning `nullptr`, and `destroyedType->getAsCXXRecordDecl()` returning `nullptr`.
=> Fix an indexer crash

src/lib/utility/file/FilePath.cpp, src/lib/utility/file/FilePath.h
Making FilePath::exists noexcept so the noexcept version of boost::filesystem::exists is used. Fixing a crash I ran into.
=> Fixing a crash in FilePath::exists

src/test/SettingsMigratorTestSuite.cpp
rename TestSettings in MigratorTestSuite so there a no double
declartions.
run cmake with -DCMAKE_UNITY_BUILD=ON
on my station the build time is around the half compared to the normal
build.
cmake 3.16 is needed for this feature 
this changes just make it possible to do the unity build
=> build: enable unity_build(optional)

src/lib/component/controller/CodeController.cpp, src/lib_gui/qt/element/code/QtCodeArea.cpp, src/lib_gui/qt/element/code/QtCodeArea.h, src/lib_gui/qt/element/code/QtCodeField.cpp, src/lib_gui/qt/element/code/QtCodeNavigator.cpp, src/lib_gui/qt/graphics/QtGraphicsView.cpp, src/lib_gui/qt/graphics/QtGraphicsView.h, src/lib_gui/qt/graphics/graph/QtGraphNode.cpp, src/lib_gui/qt/view/QtGraphView.cpp, src/lib_gui/qt/window/QtKeyboardShortcuts.cpp, src/lib_gui/qt/window/QtMainWindow.cpp
* Scroll graph area with Ctrl + Arrows
* Moved graph zoom to Ctrl + Shift + Up/Down
* Scroll code area with Ctrl + Arrows
* Fixed graph showing focus when activating the active symbol
* Made links in project description focusable
* Fixed parent graph node not showing focus after hovering edge to child node
=> ui: Fixes related to focus navigation

src/lib_cxx/data/parser/cxx/CanonicalFilePathCache.cpp, src/lib_cxx/data/parser/cxx/CanonicalFilePathCache.h, src/lib_cxx/data/parser/cxx/CxxAstVisitorComponentIndexer.cpp
=> logic: Fixed multiple main declarations not shown as separate symbols when declaring file has same name

src/lib/data/indexer/TaskExecuteCustomCommands.cpp, src/lib/data/indexer/TaskExecuteCustomCommands.h, src/test/CMakeLists.txt, src/test/CxxParserTestSuite.cpp, src/test/JavaIndexSampleProjectsTestSuite.cpp, src/test/JavaParserTestSuite.cpp, src/test/PythonIndexerTestSuite.cpp, src/test/helper/TestStorage.h
If class of a called method is explicitly specified, only record an ambiguous edge to that method.
=> logic: respect class qualifyer in method call for python post processing

src/lib/utility/file/FilePath.cpp, src/test/FilePathTestSuite.cpp
Switch from using `boost::filesystem::portable_name` and `boost::filesystem::portable_directory_name` to using `boost::filesystem::windows_name`, which allows periods and spaces in paths and filenames with extensions longer than three characters (See [boost docs](https://www.boost.org/doc/libs/1_67_0/libs/filesystem/doc/portability_guide.htm)).
fixes #957
=> logic: Less restrictions on FilePath::isValid check

src/lib_gui/qt/graphics/QtGraphicsView.cpp, src/lib_gui/qt/graphics/QtGraphicsView.h
This PR adds the context option "Save to Clipboard" to the graph viewer. It is bundled together with the "Save as Image" action.
**Motivation**
I often use Sourcetrail alongside a discussion about a design or implementation decision with colleagues.
When such a discussion happens via teleconferencing tool, sending a snapshop of the graph is very useful, but is rather long or cumbersome procedure. Either Save, pick location and name, then open chat, find file, and finally load it; or use a system tool to copy a section of the screen and paste.
With this change, the above simply turns into "Save to Clipboard, open chat, paste"
**Reviewers**
I am not really happy with the internal name `QtGraphicsView::copyGraph` and the menu item `Save to Clipboard` of this feature, but couldn't come up …
=> Add copy to clipboard

CMakeLists.txt
Worked for me with CMake 3.17, Boost 1.72.0, Qt 5.15 and Clang 10. Clang was the only issue, in that Windows loudly complained that it wasn't using C++17 native functions, so I had to silence those warnings for the LIB_CXX project. I would have silenced the warnings only within LLVM/Clang includes, but it wasn't clear to me how to do that with CMake. 
Another issue with this -- If our code or underlying code uses DenseMap, Clang has to be compiled with C++17 to work natively with C++17 host applications, or C++14 with C++14. Since the default in CMake for Clang compilation is C++14, this might cause issues or we'll have to document Clang compilation. An alternative would be that the LIB_CXX project compiles with C++14 while the rest of the app compiles with C++17 but that would make code …
=> Set C++ standard to C++17 from C++14 (See description)

src/lib/project/SourceGroup.cpp, src/lib/utility/file/FileManager.cpp, src/lib/utility/file/FilePathFilter.cpp, src/lib/utility/file/FilePathFilter.h, src/lib/utility/file/FileRegister.cpp, src/lib_cxx/project/SourceGroupCxxCdb.cpp, src/lib_cxx/project/SourceGroupCxxCodeblocks.cpp
=> src: Improved performance of FilePathFilter

src/lib_gui/qt/graphics/GraphFocusHandler.cpp, src/lib_gui/qt/view/QtGraphView.cpp
closes #1021 
Fixes a crash when switching tabs during an animation where a mouse event defocuses the focused node and moves
the focus to the parent, which is deleted after the animation ends.
=> ui: Fixed crash when changing tabs during animation

src/lib/data/indexer/TaskExecuteCustomCommands.cpp, src/lib/data/indexer/TaskExecuteCustomCommands.h, src/lib/data/storage/PersistentStorage.cpp, src/lib/data/storage/PersistentStorage.h
In multi-threaded custom command indexing errors were read from the wrong storage.
=> logic: fix error recording for multi-threaded custom command indexing

src/lib/data/indexer/TaskBuildIndex.cpp, src/lib_gui/utility/utilityApp.cpp
The non-QStringList variant of [`QProcess::start()`](https://doc.qt.io/qt-5.12/qprocess.html#start) was removed in [Qt 5.15](https://doc.qt.io/qt-5.15/qprocess.html#start)
This PR migrates the process related utilities to the `QStringList` overload, which is supported by both Qt 5.12 and 5.15.
As a bonus, the adapted method handles escaping of the arguments, which simplifies code in some locations.
This PR is essentially a salvaged part of #1082
**Reviewers:** I am using this locally with the C++ indexer on Linux. Can you please test the behaviour with the remaining indexers and on other systems?
=> Migrate QProcess::start() to QStringList

src/lib/CMakeLists.txt, src/lib/utility/messaging/type/MessageSaveAsImage.h, src/lib/utility/messaging/type/graph/MessageSaveAsImage.h, src/lib_gui/qt/graphics/QtGraphicsView.cpp, src/lib_gui/qt/graphics/QtGraphicsView.h, src/lib_gui/qt/window/QtMainWindow.cpp, src/lib_gui/qt/window/QtMainWindow.h
Resolves #426 
**How to test**:
1. Launch Sourcetrail and open any project
2. Click on graph *(see first issue)*
3. Select "Edit" -> "Save as Image" and choose a path to save
Expected result: graph image is saved at chosen path
4. Open another graph in second tab (this project or another one)
5. Click on graph on newly opened tab *(see first issue)*
6. Select "Edit" -> "Save as Image" and choose a path to save
Expected result: graph from second tab is saved at chosen path
**Issues:**
1. Graph should be clicked at least once to be marked as focused. Last focused graph is remembered to trigger saving only for needed one, not for all opened graphs.
2. `exportGraph()` direct reuse failed for me, so I copy-pasted dialog creation to QtMainWindow.cpp. The issue was in GLib assertions like this: …
=> feat: menu action for graph 'save as image'

src/lib_gui/CMakeLists.txt, src/lib_gui/qt/element/code/QtCodeArea.cpp, src/lib_gui/qt/utility/compatibilityQt.cpp, src/lib_gui/qt/utility/compatibilityQt.h
This PR adds a compatability layer to bridge compatability between Qt version.
I added this as a separate file to simplify future migrations in case the minimum version changes.
Currently this only contains a compatability wrapper for `QWheelEvent::globalPos()`, which was deprecated in Qt 5.14.
This allows to compile Sourcetrail with Qt versions 5.12 - 5.15.
Longer discussion against the full migration: #975
=> Add compatibility layer for Qt versions

src/lib_gui/qt/window/QtMainWindow.cpp
This is done because users may already be used to "preferences" being the bottom-most button and may accidentally click "Save Graph as Image..." when they actually want to open the preferences screen.
=> ui: move "Save Graph as Image..." up in "Edit" menu to keep "Preferences..." at the bottom

src/lib/data/indexer/TaskBuildIndex.cpp, src/lib_gui/utility/path_detector/maven_executable/MavenPathDetectorWindows.cpp, src/lib_gui/utility/utilityApp.cpp
The reverted change has caused the Linux release to fail at indexing any Python project
=> src: revert migration of QProcess::start() to QStringList

src/lib_gui/utility/path_detector/java_runtime/JavaPathDetectorLinux.cpp
readlink was being invoked as `"readlink" "-f path/to/java"`. It should've been `"readlink" "-f" "path/to/java"` instead.
This can verified by running the tests and looking at the output of the following command:
$ sudo execsnoop -q | grep readlink
readlink         2060   1925     0 "/nix/store/0y7rv26ffa359wvqd3js94cn73z882fg-coreutils-8.32/bin/readlink" "-f /nix/store/d5mpdil4c8z466f9zyxywxg5lm2zk3ls-openjdk-8u272-b10-jre/bin/java"
readlink         2081   1925     0 "/nix/store/0y7rv26ffa359wvqd3js94cn73z882fg-coreutils-8.32/bin/readlink" "-f /nix/store/xr5xm2bmfhd02v8h9ghzmhbcdc49ms55-openjdk-8u272-b10/lib/openjdk/jre/bin/java"
=> fix: java path detection failures on linux

setup/Linux/data/package/Sourcetrail.sh
Sourcetrail.sh recursively resolves its path wrt (possible) symlinks, to determine actual directory where sourcetrail is installed. We can simplify such resolution using  Linux flavour of "readlink" command (Sourcetrail.sh is for Linux, anyway).
=> Simplify/cleanup symbolic link resolution in Sourcetrail launch script for Linux

bin/test/data/SourceGroupTestSuite/custom_command/expected_output/output_unix.txt, bin/test/data/SourceGroupTestSuite/custom_command/expected_output/output_windows.txt, script/download_python_indexer.sh, src/app/main.cpp, src/lib/app/paths/ResourcePaths.cpp, src/lib/app/paths/ResourcePaths.h, src/lib/data/indexer/IndexerCommandCustom.cpp, src/lib/data/indexer/IndexerCommandCustom.h, src/lib/data/indexer/TaskBuildIndex.cpp, src/lib/data/indexer/TaskExecuteCustomCommands.cpp, src/lib/project/SourceGroupCustomCommand.cpp, src/lib_gui/qt/project_wizard/content/QtProjectWizardContentSelect.cpp, src/lib_gui/qt/project_wizard/content/path/QtProjectWizardContentPathPythonEnvironment.cpp, src/lib_gui/utility/path_detector/cxx_header/CxxFrameworkPathDetector.cpp, src/lib_gui/utility/path_detector/cxx_header/CxxHeaderPathDetector.cpp, src/lib_gui/utility/path_detector/cxx_header/CxxVs15HeaderPathDetector.cpp, src/lib_gui/utility/path_detector/cxx_header/utilityCxxHeaderDetection.cpp, src/lib_gui/utility/path_detector/cxx_header/utilityCxxHeaderDetection.h, src/lib_gui/utility/path_detector/java_runtime/JavaPathDetectorLinux.cpp, src/lib_gui/utility/path_detector/java_runtime/JavaPathDetectorMac.cpp, src/lib_gui/utility/path_detector/maven_executable/MavenPathDetectorUnix.cpp, src/lib_gui/utility/path_detector/maven_executable/MavenPathDetectorWindows.cpp, src/lib_gui/utility/utilityApp.cpp, src/lib_gui/utility/utilityApp.h, src/lib_java/utility/utilityMaven.cpp, src/lib_python/project/SourceGroupPythonEmpty.cpp, src/test/PythonIndexerTestSuite.cpp, src/test/SourceGroupTestSuite.cpp
* changed implementation of executeProcess
* unified all different implementations of executeProcess
* separated arg list from command for all calls of executeProcess (this also required to remove quotes that were added to path args because otherwise the Python indexer would mistake absolute paths for relative paths.)
* update expected output for custom command tests
=> src: switch from Qt to boost implementation of executeProcess

src/lib/data/HierarchyCache.cpp, src/lib/data/HierarchyCache.h
The old implementation produces several multi-inheritance edges between two classes if there are multiple inheritance paths between them due to multiple inheritance diamonds. The new implementation produces only one edge in such a case.
Also, the old implementation has performance issues when there is a huge number of inheritance paths starting at the focused class. With a pathological multiple inheritance class structure, the number of paths can be exponential in the number of involved classes. The new implementation solves this issue by considering subgraphs instead of paths.
---
I have a project (which, unfortunately, I cannot share as is) where the previous implementation seemingly got stuck within `addInheritanceEdgesRecursive` when looking up a specific symbol. With this change, the …
=> src: fix multi-level inheritance edges when there are diamonds

src/lib/utility/file/FileSystem.cpp, src/test/FileSystemTestSuite.cpp
boost::filesystem::canonical causes issues on Windows and will throw an exception if path is too long.
=> remove call to boost::filesystem::canonical when preparing indexer (issue #1149)

README.md
With #775 Boost was downgraded to 1.67 (from 1.68).
With pull request #807 the readme file was corrected. But this correction was not complete. The example path for the -DBOOST_ROOT parameter of cmake was left unchanged.
This inconsistency took me some time to understand. So I propose to adapt the path also.
=> Adapt cmake -DBOOST_ROOT path in README to reflect downgrade of boost

script/download_python_indexer.sh, src/lib/data/indexer/TaskExecuteCustomCommands.cpp, src/lib/utility/text/TextAccess.cpp, src/lib/utility/text/TextAccess.h
* before this update the SourcetrailPythonIndexer was saving indexed code to the database different than Sourcetrail, which could result in crashes
=> logic: update SourcetrailPythonIndexer to version 1.25.6 to fix TextAccess issue

script/deploy_windows.sh
https://github.com/CoatiSoftware/Sourcetrail/pull/1162#discussion_r593389410
`timstamp` is an 8.3 thing, but Verisign's `timstamp` endpoint died ages ago. You can pick any replacement you like. Symantec is roughly of similar caliber to Verisign, hence the choice. But it doesn't really matter to me.
It's also fine to split this out, as it's a behavior change -- albeit from "using a service that doesn't exist at all":
```
curl -vvv http://timestamp.verisign.com/scripts/timstamp.dll
*   Trying 216.168.248.38...
* TCP_NODELAY set
* Connection failed
* connect to 216.168.248.38 port 80 failed: Network is unreachable
* Failed to connect to timestamp.verisign.com port 80: Network is unreachable
* Closing connection 0
curl: (7) Failed to connect to timestamp.verisign.com port 80: Network is …
```
=> Replace timestamp endpoint

src/lib_gui/qt/element/code/QtCodeArea.cpp
fix #1201 where setting the background color for line numbers in color_scheme is ignored.
=> fix #1201 - color_scheme <line_number><background> ignored

src/lib_cxx/data/parser/cxx/ClangInvocationInfo.cpp
This PR adds support for LLVM 12.
The title of the driver was integrated into the constructor: https://github.com/llvm/llvm-project/commit/257b29715bb27b7d9f6c3c40c481b6a4af0b37e5
=> Add support for LLVM 12

bin/app/data/java/gradle/init.gradle
Gradle 7 drops support of the depracated `compile`/`testCompile` configurations - `compileClasspath`/`testCompileClasspath` can be used instead.
(It might be worth to remove support for `compile`/`testCompile` configurations instead, but that would potentially break things for users of ancient Gradle versions.)
=> support Gradle 7 when copying (test) compile libs

docs/documentation/index.html
The `Use` section was misaligned due to unclosed html tag in the list.
=> docs: missing close list tag added
