- src/lib/project/Project.cpp
> src: getRefreshInfo() always return a value

- cmake/version.cmake
This fixes building with the tarball source.
> Add a version if not in git

- appveyor.yml
The CI will build the entire project on Windows (currently without language support) and run all applicable tests.
> Add Appveyor based CI

- CMakeLists.txt
> build: Downgraded Boost to 1.67

- cmake/linux_package.cmake
> build: Install SourcetrailPythonIndexer only if it is build

- README.md
See commit cca66470 in pull request #775.
> Correct the required Boost version in the Readme

- CMakeLists.txt
This is needed to build successfully on openSUSE.
> build: Link to LIB_GUI_PROJECT

- bin/app/data/color_schemes/bad_rainbow.xml
- bin/app/data/color_schemes/bright.xml
- bin/app/data/color_schemes/dark.xml
- bin/app/data/gui/code_view/code_view.css
- bin/app/data/gui/custom_trail_view/custom_trail_view.css
- bin/app/data/gui/tooltip_view/tooltip_view.css
- src/lib/settings/ColorScheme.cpp
- src/lib_gui/qt/utility/utilityQt.cpp
- src/lib_gui/qt/view/QtErrorView.cpp
- src/lib_gui/qt/view/QtStatusView.cpp
* fixed issues where color scheme entries were missing
* removed color scheme entries for nodes and edges that do not exist anymore
> logic: color scheme fixes

- CMakeLists.txt
> build: Changes to compile on Debian Buster

- docs/documentation/index.html
Hi!
Im submitting this pull request for changes I made to the documentation:
- Added a *Welcome* section that includes an overview with the short description for Sourcetrail and also added the Supported Languages section here.
- Re-structured the content flow - moved some sections around such as the one mentioned above and the FAQ to the bottom. 
*Side note:* It may be nice to add more common questions people have asked here in the past with the answers.
- Re-phrased/re-worded some sentences and paragraphs and fixed minor grammar issues. 
My next steps: I plan to continue going through each section and making changes. I also would like to edit the photos provided by squaring/circling the name of things when discussing them. Lastly, I eventually want to add a tutorial section where we …
> Sourcetrail documentation edit phase 1

- script/download_python_indexer.sh
- src/lib_python/project/SourceGroupPythonEmpty.cpp
update python indexer to make it accept Windows Python environment with python.exe in root directory (issue #771)
> update python indexer to fix issue #771

- src/lib/CMakeLists.txt
- src/lib/settings/source_group/type/SourceGroupSettingsUnloadable.cpp
- src/lib/settings/source_group/type/SourceGroupSettingsUnloadable.h
- src/lib_gui/qt/project_wizard/content/QtProjectWizardContentUnloadable.cpp
* improve comparison to respect all values
* improved UI to display the source group type
> logic: improved handling of unloadable source group

- CMakeLists.txt
Fix for Issue 870
https://github.com/CoatiSoftware/Sourcetrail/issues/870
> build: creation of symlinks was broken, race condition.

- src/lib/CMakeLists.txt
- src/lib/app/Application.cpp
- src/lib/component/controller/UndoRedoController.cpp
- src/lib/component/controller/UndoRedoController.h
- src/lib/component/view/MainView.h
- src/lib/utility/messaging/type/MessageRefreshUIState.h
- src/lib_gui/qt/element/code/QtCodeNavigator.cpp
- src/lib_gui/qt/element/code/QtCodeNavigator.h
- src/lib_gui/qt/view/QtCodeView.cpp
- src/lib_gui/qt/view/QtMainView.cpp
- src/lib_gui/qt/view/QtMainView.h
Separated UI refresh into style and state refresh to avoid race condition in code view state.
fixes #916
> ui: Refresh UI state after all style refreshes in each view

- src/lib/utility/file/FilePath.cpp
- src/test/FilePathTestSuite.cpp
* fixed bug that caused filepaths to be invalid for files with extension
* added tests for FilePath::isValid()
> Fix and add tests for FilePath::isValid()

- src/lib_gui/qt/utility/QtThreadedFunctor.h
* It happens when executed both from Qt and TaskScheduler thread in parallel.
* I found that the signal within QtThreadedFunctorHelper::operator() was sometimes not emitted and therefore QtThreadedFunctorHelper::execute() was never called.
fixes #924
> src: Fixed QtThreadedFunctor gets sometimes stuck

- src/lib/component/controller/CodeController.cpp
- src/lib/component/controller/CodeController.h
- src/lib/utility/messaging/type/code/MessageToNextCodeReference.h
- src/lib_gui/qt/element/code/CodeFocusHandler.cpp
- src/lib_gui/qt/element/code/CodeFocusHandler.h
- src/lib_gui/qt/element/code/QtCodeArea.cpp
- src/lib_gui/qt/element/code/QtCodeArea.h
- src/lib_gui/qt/element/code/QtCodeFileList.cpp
- src/lib_gui/qt/element/code/QtCodeFileSingle.cpp
- src/lib_gui/qt/element/code/QtCodeNavigator.cpp
- src/lib_gui/qt/window/QtKeyboardShortcuts.cpp
* Take care of both symbol and local symbol references within the same line
* Also use Left/Right navigation for active references
> ui: Iterate code references within the same line

- src/lib_gui/qt/element/code/QtCodeArea.cpp
- src/lib_gui/qt/element/code/QtCodeArea.h
- src/lib_gui/qt/element/code/QtCodeFile.cpp
- src/lib_gui/qt/element/code/QtCodeFile.h
- src/lib_gui/qt/element/code/QtCodeFileList.cpp
- src/lib_gui/qt/element/code/QtCodeFileList.h
- src/lib_gui/qt/element/code/QtCodeFileSingle.cpp
- src/lib_gui/qt/element/code/QtCodeFileSingle.h
- src/lib_gui/qt/element/code/QtCodeNavigateable.h
- src/lib_gui/qt/element/code/QtCodeNavigator.cpp
- src/lib_gui/qt/element/code/QtCodeSnippet.cpp
- src/lib_gui/qt/element/code/QtCodeSnippet.h
> ui: Fix copy shortcut for selected code broken

- src/lib/app/Application.cpp
- src/lib/settings/ApplicationSettings.cpp
- src/lib/settings/ApplicationSettings.h
- src/lib_gui/qt/view/QtMainView.cpp
- src/lib_gui/qt/window/QtMainWindow.cpp
- src/lib_gui/qt/window/QtMainWindow.h
- src/lib_gui/qt/window/QtStartScreen.cpp
> ui: Refactored recent projects menu

- src/lib/data/indexer/TaskExecuteCustomCommands.cpp
- src/test/PythonIndexerTestSuite.cpp
if a method call is qualified with "super()" only record edges pointing to the base class of the context of the callee
> respect "super()" in python post processing

- bin/app/data/ProjectSettings_template.xml
Trivial fix: changed closing tag of `exclude_path` from `source_path` to `exclude_path`.
> Copy paste typo fix in ProjectSettings_template.xml

- docs/documentation/index.html
- src/lib_gui/qt/project_wizard/content/QtProjectWizardContentPreferences.cpp
- src/lib_gui/utility/path_detector/java_runtime/JavaPathDetectorMac.cpp
> java: Updated Java path detector and docs to current JDK file structure on macOS

- deployment/dockerfiles/README.md
- deployment/dockerfiles/linux/centos7_64/Dockerfile
- deployment/dockerfiles/linux/travis_ci/Dockerfile
> build: Updated Travis CI docker image to LLVM/Clang 10.0.0

- src/lib/settings/ApplicationSettings.cpp
- src/lib/settings/ApplicationSettings.h
- src/lib_gui/qt/utility/QtFileDialog.cpp
- src/lib_gui/qt/utility/QtFileDialog.h
> logic: save last filepicker location

- src/lib/settings/ApplicationSettings.cpp
- src/lib/settings/ApplicationSettings.h
- src/lib_gui/qt/graphics/QtGraphicsView.cpp
> feat: remember graph zoom level on restart

- src/lib_cxx/utility/codeblocks/CodeblocksTarget.cpp
> Check if compiler is null in CodeblocksTarget

- src/test/CxxParserTestSuite.cpp
This reverts commit e3c0ed934988caaea244018f3ba72fc04c8cbbce.
> Revert "Revert "test: fix expected output for CXX indexer tests""

- deployment/dockerfiles/README.md
indented code 4 spaces
I don't need to be added to the AUTHORS.txt for this tweak
> Markdown formatting of code

- src/lib_gui/utility/utilityApp.cpp
This PR fixes an issue with `boost::process::child::wait_for`, which waits the full timeout if the process has already exited.
The wrapper can easily reverted back once this issue is fixed in Boost.process.
Solves #1180
> Fix extensive wait for short-lived processes
